//! Kill Switch (网络锁) 模块
//! 
//! 使用 macOS pf 防火墙实现 Kill Switch 功能
//! 当 VPN 断开时阻断所有网络流量，防止真实 IP 泄露
//!
//! **Feature: vpn-pure-mode**
//! **Validates: Requirements 2.2, 2.3, 2.4, 2.6, 2.7**

use std::fs;
use std::path::PathBuf;
use std::process::Command;
use std::sync::atomic::{AtomicBool, Ordering};
use tracing::{error, info, warn};

use crate::constants::get_cache_dir;

/// Kill Switch 状态文件路径
fn get_killswitch_rules_file() -> PathBuf {
    get_cache_dir().join("tovpn-killswitch.rules")
}

/// Kill Switch 状态标记文件
fn get_killswitch_state_file() -> PathBuf {
    get_cache_dir().join("tovpn-killswitch.state")
}

/// 全局 Kill Switch 状态
static KILLSWITCH_ENABLED: AtomicBool = AtomicBool::new(false);

/// Kill Switch 管理器
pub struct KillSwitch;

impl KillSwitch {
    /// 检查 Kill Switch 是否已启用
    pub fn is_enabled() -> bool {
        KILLSWITCH_ENABLED.load(Ordering::SeqCst)
    }

    /// 启用 Kill Switch
    /// 
    /// **Feature: vpn-pure-mode**
    /// **Validates: Requirements 2.2 - 连接时启用防火墙规则阻断非 VPN 流量**
    pub fn enable() -> Result<(), String> {
        if Self::is_enabled() {
            info!("Kill Switch already enabled");
            return Ok(());
        }

        info!("Enabling Kill Switch...");

        // 生成 pf 规则
        let rules = Self::generate_rules();
        let rules_file = get_killswitch_rules_file();

        // 写入规则文件
        fs::write(&rules_file, &rules)
            .map_err(|e| format!("Failed to write rules file: {}", e))?;

        // 加载规则到 pf
        let output = Command::new("/usr/bin/sudo")
            .args(["-n", "-k", "/sbin/pfctl", "-f", rules_file.to_str().unwrap()])
            .output()
            .map_err(|e| format!("Failed to load pf rules: {}", e))?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            // pf 可能输出警告但仍然成功
            if !stderr.contains("No ALTQ support") {
                warn!("pfctl output: {}", stderr);
            }
        }

        // 启用 pf
        let output = Command::new("/usr/bin/sudo")
            .args(["-n", "-k", "/sbin/pfctl", "-e"])
            .output()
            .map_err(|e| format!("Failed to enable pf: {}", e))?;

        // pf 可能已经启用，忽略 "already enabled" 错误
        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            if !stderr.contains("already enabled") {
                return Err(format!("Failed to enable pf: {}", stderr));
            }
        }

        // 标记状态
        KILLSWITCH_ENABLED.store(true, Ordering::SeqCst);
        let _ = fs::write(get_killswitch_state_file(), "enabled");

        info!("Kill Switch enabled successfully");
        Ok(())
    }

    /// 禁用 Kill Switch
    /// 
    /// **Feature: vpn-pure-mode**
    /// **Validates: Requirements 2.4 - 禁用时移除所有防火墙规则**
    pub fn disable() -> Result<(), String> {
        if !Self::is_enabled() && !get_killswitch_state_file().exists() {
            info!("Kill Switch already disabled");
            return Ok(());
        }

        info!("Disabling Kill Switch...");

        // 刷新 pf 规则（恢复默认）
        let output = Command::new("/usr/bin/sudo")
            .args(["-n", "-k", "/sbin/pfctl", "-F", "all"])
            .output()
            .map_err(|e| format!("Failed to flush pf rules: {}", e))?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            warn!("pfctl flush warning: {}", stderr);
        }

        // 禁用 pf（可选，某些系统可能需要保持 pf 运行）
        // 这里我们只清除规则，不完全禁用 pf
        // let _ = Command::new("/usr/bin/sudo")
        //     .args(["-n", "-k", "/sbin/pfctl", "-d"])
        //     .output();

        // 清理状态文件
        let _ = fs::remove_file(get_killswitch_rules_file());
        let _ = fs::remove_file(get_killswitch_state_file());

        KILLSWITCH_ENABLED.store(false, Ordering::SeqCst);

        info!("Kill Switch disabled successfully");
        Ok(())
    }

    /// 生成 pf 防火墙规则
    /// 
    /// **Feature: vpn-pure-mode**
    /// **Validates: Requirements 2.6, 2.7 - 允许 localhost 和 LAN 流量**
    fn generate_rules() -> String {
        // pf 规则说明：
        // 1. 允许 loopback 接口的所有流量 (localhost)
        // 2. 允许 LAN 流量 (RFC1918 私有地址)
        // 3. 允许 utun 接口的所有流量 (VPN 隧道)
        // 4. 阻断其他所有出站流量
        r#"# ToVPN Kill Switch Rules
# Generated by ToVPN - Do not edit manually

# 允许 loopback 接口 (localhost 127.0.0.1)
pass quick on lo0 all

# 允许 VPN 隧道接口 (utun*)
pass quick on utun0 all
pass quick on utun1 all
pass quick on utun2 all
pass quick on utun3 all
pass quick on utun4 all
pass quick on utun5 all
pass quick on utun6 all
pass quick on utun7 all
pass quick on utun8 all
pass quick on utun9 all

# 允许 LAN 流量 (RFC1918 私有地址范围)
# 10.0.0.0/8
pass quick from any to 10.0.0.0/8
pass quick from 10.0.0.0/8 to any

# 172.16.0.0/12
pass quick from any to 172.16.0.0/12
pass quick from 172.16.0.0/12 to any

# 192.168.0.0/16
pass quick from any to 192.168.0.0/16
pass quick from 192.168.0.0/16 to any

# 允许 link-local 地址 (169.254.0.0/16)
pass quick from any to 169.254.0.0/16
pass quick from 169.254.0.0/16 to any

# 允许多播地址
pass quick from any to 224.0.0.0/4
pass quick from any to 239.0.0.0/8

# 允许 DHCP (获取 IP 地址)
pass quick proto udp from any port 68 to any port 67
pass quick proto udp from any port 67 to any port 68

# 允许已建立的连接（入站响应）
pass in quick proto tcp flags A/A
pass in quick proto udp

# 阻断所有其他出站流量
block out quick on en0 all
block out quick on en1 all
block out quick on en2 all
block out quick on en3 all
block out quick on en4 all
block out quick on en5 all

# 默认阻断
block all
"#.to_string()
    }

    /// 检查 Kill Switch 状态（从文件恢复）
    /// 
    /// 用于应用启动时检查是否有残留的 Kill Switch 状态
    #[allow(dead_code)]
    pub fn check_state() -> bool {
        get_killswitch_state_file().exists()
    }

    /// 强制清理 Kill Switch（应用退出时调用）
    /// 
    /// **Feature: vpn-pure-mode**
    /// **Validates: Requirements 2.5 - 应用退出时禁用 Kill Switch 并恢复网络**
    pub fn force_cleanup() {
        info!("Force cleaning up Kill Switch...");
        
        // 无论当前状态如何，都尝试清理
        let _ = Command::new("/usr/bin/sudo")
            .args(["-n", "-k", "/sbin/pfctl", "-F", "all"])
            .output();

        // 清理状态文件
        let _ = fs::remove_file(get_killswitch_rules_file());
        let _ = fs::remove_file(get_killswitch_state_file());

        KILLSWITCH_ENABLED.store(false, Ordering::SeqCst);

        info!("Kill Switch force cleanup completed");
    }
}

/// 在模块卸载时确保清理
impl Drop for KillSwitch {
    fn drop(&mut self) {
        if Self::is_enabled() {
            if let Err(e) = Self::disable() {
                error!("Failed to disable Kill Switch on drop: {}", e);
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_rules_generation() {
        let rules = KillSwitch::generate_rules();
        
        // 验证规则包含必要的部分
        assert!(rules.contains("pass quick on lo0 all"), "Should allow loopback");
        assert!(rules.contains("pass quick on utun"), "Should allow utun interfaces");
        assert!(rules.contains("10.0.0.0/8"), "Should allow 10.x.x.x LAN");
        assert!(rules.contains("172.16.0.0/12"), "Should allow 172.16.x.x LAN");
        assert!(rules.contains("192.168.0.0/16"), "Should allow 192.168.x.x LAN");
        assert!(rules.contains("169.254.0.0/16"), "Should allow link-local");
        assert!(rules.contains("block"), "Should have block rules");
    }

    #[test]
    fn test_state_file_paths() {
        let rules_file = get_killswitch_rules_file();
        let state_file = get_killswitch_state_file();
        
        assert!(rules_file.to_string_lossy().contains("tovpn-killswitch.rules"));
        assert!(state_file.to_string_lossy().contains("tovpn-killswitch.state"));
    }
}
